name: Snyk SCA and SAST Scan

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly on Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install snyk-to-html # for reports
        run: npm install -g snyk-to-html

      - name:  Authenticate Snyk CLI
        env:
          SNYK_API: https://app.snyk.io/api  # SNYK-US-01 - Use https://api.us.snyk.io for SNYK-US-02
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk Code scan
        continue-on-error: true
        # run: snyk code test --severity-threshold=low
        run: snyk code test --severity-threshold=low --json || true

      - name: Run Snyk open source scan
        continue-on-error: true
        # run: snyk test --severity-threshold=low --all-projects
        run: snyk test --severity-threshold=low --all-projects --json|| true

      - name: Upload Snyk HTML reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk-code-report.html
            snyk-sca-report.html
